version: "3"

services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - node-net
    volumes:
      - ./node:/usr/src/app
    ports:
      - "3000:3000"
    tty: true
    # depends_on:
    #   - db
  db:
    image: mysql:5.7
    command: --innodb_use_native_aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - "./mysql:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root
    networks:
      - node-net

networks:
  node-net:
    driver: bridge
